chaoss/grimoirelab-graal

README.md, graal/backends/core/cocom.py
- Fix python interface example of `CoCom` backend under documentation. [Reference](https://github.com/Bitergia/graal/blob/c1dfb0f38183766e69d608cf44ac17d26a3ac47d/graal/backends/core/cocom.py#L75)
- Fix parameter definition. [Reference](https://github.com/Bitergia/graal/blob/c1dfb0f38183766e69d608cf44ac17d26a3ac47d/graal/backends/core/cocom.py#L59)
@jgbarah @valeriocos Please review and let me know if any changes required 😄
=> [doc] Fix documentation example error

README.md
This code fixes the url of the travis badge, which was missing the organization part.
=> [doc] Fix travis badge in README.md

bin/graal
~~I ran graal from the terminal and the following warning popped up:~~
~~This code is about fixing that warning by using `ConfigParser` class instead of `SafeConfigParser`.~~
EDIT: Removed the unused code to pass a config file through command line while running graal.
=> [graal] Remove unused config_file option

graal/graal.py
Remove the default value of the `exec_path` in the class `GraalCommandArgumentParser` and fix its help message.
=> [graal] Fix `exec_path` param in `GraalCommandArgumentParser`.

graal/graal.py
This code aligns the signature of the method `metadata` to the corresponding one in Perceval, which was modified to allow filtering sensitive attributes retrieved from a data source (commit in perceval: 1effaa0).
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
=> [graal] Align metadata method with perceval one

graal/_version.py
Graal is now a part of GrimoireLab releases.
To be properly included, very new release of it needs to increase this number.
I'm increasing it, since it was not touched during the last year...
Signed-off-by: Jesus M. Gonzalez-Barahona <jgb@gsyc.es>
=> [Release] 0.2.0

.travis.yml, README.md, graal/backends/core/analyzers/scancode.py, graal/backends/core/colic.py, tests/test_colic.py, tests/test_scancode.py, tests/utils.py
Addresses: #27 
@valeriocos In reference to your PR. This contains some minor changes. 
Still, there are some improvements which can be made and tests should be added accordingly.
Please do have a look, Thanks :)
Work attributions: @valeriocos 's #28
=> Add support of scancode_cli to CoLic Backend ( WIP )

graal/graal.py, tests/test_graal.py
I've added tests wrt to PR #31 
@valeriocos Please do let me know if any changes required 
Thanks :)
=> [graal] Derive `git_path` from `uri`

graal/backends/core/analyzers/lizard.py, graal/backends/core/cocom.py, tests/test_cocom.py, tests/test_lizard.py
A repository level analysis implementation for CoCom Backend via Lizard. 
This implementation doesn't harm the `incremental fetches` (which was one of the issues with implementation proposed in  #38)
**Evaluation:**
| Repository   | Number of Commits |  *File Level           | Repository Level  |
| :-------------: | :---------: |:-------------: | :-----:|
| [chaoss/grimoirelab-perceval]()| 1387 | 23.65 min |  27.97 min |
| [chaoss/grimoirelab-sirmordred]() | 869 | 9.69 min | 4.27 min |
| [chaoss/grimoirelab-graal]()   | 169 |  1.73 min  | 0.90 min |
@valeriocos Please do have a look when you get time. Thanks :)
**WIP**
Closes #36 
Signed-off-by: inishchith <inishchith@gmail.com>
=> [cocom] Add repository level analysis via lizard

README.md
@valeriocos This is a quick update to the documentation after addition of new/updated category to the backends. Also, added links to the requirements; Do let me know if any changes required :)
Thanks!
Signed-off-by: inishchith <inishchith@gmail.com>
=> [docs] Update documentation and links to requirements

graal/backends/core/analyzers/scancode.py, graal/backends/core/colic.py, tests/test_colic.py, tests/test_scancode.py
> I had noticed that the structure of analysis(for code_license_scancode_cli ) is different(dict) as compared to other categories (list). Sorry for the mistake. 
@valeriocos Please do have a look :)
Signed-off-by: inishchith <inishchith@gmail.com>
=> [analyzer] Fix scancode_cli results

tests/test_graal.py
This code aligns the test_init to the recent changes in the Git Perceval backend: perceval/b311541
=> [tests] Fix test_init in test_graal

graal/backends/core/analyzers/cloc.py, tests/test_cloc.py
@valeriocos As I was working on large repository evaluation(https://github.com/inishchith/gsoc-graal/issues/12#issuecomment-513395968), enter this error in logic under `cloc` analyzer which depends on reporting of results based on position in the list.
- For instance, in the following example 3rd element:
1. represents number of blank lines (int)
2. here it's part of language name (str)
```
i. ['YAML', '1', '3', '0', '16']
ii. ['Bourne', 'Again', 'Shell', '1', '13', '18', '105']   <--------- Error
```
This PR fixes the error by picking the elements from the last(right to left). Please let me know what you think :)
Signed-off-by: inishchith <inishchith@gmail.com>
=> [cloc] Fix cloc error due to mulitple word language-name

graal/backends/core/analyzers/lizard.py
This code ignores the deprecation warnings created by lizard_ext/auto_open.py at line 26, and thrown when calling lizard.analyze_file within the `__analyze_file` method in analyzers/lizard.
=> [analyzers] Suppress deprecation warning lizard.analyze_file

graal/backends/core/analyzers/cloc.py, tests/test_cloc.py
This code increases the `diff_timeout` value to cope with diff calculation for large files (mostly
javascript ones). Cloc analyzer version and tests have been updated accordingly.
=> [analyzer] Add `diff_timeout` param to cloc analyzer

graal/backends/core/colic.py
This PR filters directory paths and softlinks from the colic analysis. This change is needed to prevent failures in scancode-cli (issue #55).
Backend version is now set to 0.5.2
=> [colic] Filter dir paths and softlinks from analysis

graal/graal.py
This PR addresses #56, thus it modifies the command used to checkout of a commit by adding the option `-f`, which throws away local changes.
Graal version is set to 0.4.1
=> [graal] Force checkout command

graal/backends/core/cocom.py, graal/backends/core/codep.py, graal/backends/core/colang.py, graal/backends/core/colic.py, graal/backends/core/coqua.py, graal/backends/core/covuln.py, graal/graal.py, tests/test_cocom.py, tests/test_codep.py, tests/test_colang.py, tests/test_colic.py, tests/test_coqua.py, tests/test_covuln.py, tests/test_graal.py
This code changes the signature of the class `BackendCommandArgumentParser`,
which now accepts as first parameter the backend object instead
its categories. This change is needed to simplify accessing other backend
attributes, beyond the categories.
All backends and corresponding tests have been updated.
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
=> [backend] Change signature BackendCommandArgumentParser

graal/graal.py, tests/test_graal.py
This code replaces the git command with its full path. This change is needed since for some repositories such as `git` and `mysql-server`, the git checkout command wasn't found.
=> [graal] Replace git cmd with /usr/bin/git

README.md, requirements.txt, setup.py
Due to an error in the latest version of lizard (1.17.x), graal fails during the instalation. This commit fixes that error pinning the lizard version to 1.16.6.
=> Fix lizard package dependency

graal/graal.py
This code uses the backend name to initialize the directory where the git repo will be cloned. This change is need to allow Graal to clone the same repo (that could be used by different backends) in different local paths.
Graal version is now 0.5.4
Related to #86
=> [graal] Use backend name to init default git path

graal/backends/core/cocom.py, tests/test_cocom.py
This code includes the `parents` info to the documents returned by the cocom backend. This change is needed to allow navigate the commit graph on the cocom data.
Tests have been updated accordingly.
Backend version is now 0.5.0
=> [cocom] Include parents info in docs generated

graal/backends/core/cocom.py, tests/test_cocom.py
This code includes the `files` info to the documents returned by the cocom backend. This change is needed to have a global view over all files in a git revision
Tests have been updated accordingly.
Backend version is now 0.6.0
=> [cocom] Include files info in docs generated

.travis.yml
This code aims at aligning the CI tests across the different grimoirelab components.
Python 3.5 is removed as its support period has ended and Python 3.6, 3.7 and 3.8 are now supported.
The version of setuptools and pip has been downgraded as a hotfix to solve the failing CI tests.
The version of Go is updated to the most stable version to align it with the scc tool requirement.
=> [travis] Update .travis.yml

.github/workflows/release.yml, .github/workflows/tests.yml, poetry.lock, pyproject.toml, releases/unreleased/drop-python-3.6-support.yml, releases/unreleased/include-requirements-for-development.yml, requirements_dev.txt
This PR updates the dependencies of Graal using the version number of the packages instead of the master branch.
It also includes a `requirements_dev.txt` file to install the development version of the grimoirelab packages for tests.
This PR also fixes the tests that were failing when installing a Go package.
=> Update requirements for Graal and fix tests

.github/workflows/tests.yml, poetry.lock, pyproject.toml, releases/unreleased/update-flake8-dependencies.yml
This PR updates the dependency of flake8 to be ^4.0.1 similar to other Grimoirelab repositories and avoids errors with new versions.
=> [deps] Update flake8 dependency

.github/workflows/release.yml
Fix ruby GitHub action. It was using the wrong action name.
=> [gha] Fix Ruby GitHub action name

.github/workflows/release.yml, .github/workflows/tests.yml, poetry.lock, pyproject.toml
There was a mistake in the Perceval release that caused version 2.x to be created. This commit updates poetry.lock to downgrade the Perceval version that was incorrectly released.
=> Fix Perceval version in poetry.lock
